# Generated by Django 3.2.25 on 2024-07-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone', models.CharField(blank=True, max_length=20)),
                ('default_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('default_city', models.CharField(blank=True, max_length=50)),
                ('default_address_1', models.CharField(blank=True, max_length=75)),
                ('default_address_2', models.CharField(blank=True, max_length=75, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
