# Generated by Django 3.2.25 on 2024-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240702_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='default_county',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
