# Generated by Django 3.2.25 on 2024-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OG_shoppingbag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=250),
        ),
    ]
