# Generated by Django 3.2.25 on 2024-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='writer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
